gitbusylivin usr/bin
debian/gitbusylivin.1 usr/share/man/man1
GitBusyLivin.desktop usr/share/applications
debian/icons/16x16/apps/gitbusylivin.png usr/share/icons/hicolor/16x16/apps
debian/icons/16x16/apps/gitbusylivin.png usr/share/icons/gnome/16x16/apps
debian/icons/32x32/apps/gitbusylivin.png usr/share/icons/hicolor/32x32/apps
debian/icons/32x32/apps/gitbusylivin.png usr/share/icons/gnome/32x32/apps
debian/icons/64x64/apps/gitbusylivin.png usr/share/icons/hicolor/64x64/apps
debian/icons/64x64/apps/gitbusylivin.png usr/share/icons/gnome/64x64/apps
debian/icons/128x128/apps/gitbusylivin.png usr/share/icons/hicolor/128x128/apps
debian/icons/128x128/apps/gitbusylivin.png usr/share/icons/gnome/128x128/apps
debian/icons/256x256/apps/gitbusylivin.png usr/share/icons/hicolor/256x256/apps
debian/icons/256x256/apps/gitbusylivin.png usr/share/icons/gnome/256x256/apps
debian/icons/512x512/apps/gitbusylivin.png usr/share/icons/hicolor/512x512/apps
debian/icons/512x512/apps/gitbusylivin.png usr/share/icons/gnome/512x512/apps

