.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2018 Haydar Alkaduhimi <haydr@hosting4all.com>,
.\"
.TH Gitbusylivin 1 "May 20 2018"
.SH NAME
gitbusylivin \- A Qt git client using libgit2 
.SH SYNOPSIS
.B gitbusylivin
.SH DESCRIPTION
A Qt git client using libgit2
.B gitbusylivin
